### ISSUE TITLE
Setup Semantic Release

### ISSUE THREAD

**Issue by joshuawilson** [fabric8-ui/fabric8-runtime-console#80]
Most of the code is in place for Semantic Release but there is no pipeline for it yet. 

Configure a pipeline to release the module when the correct syntax is used in the commit message.

**Comment by jstrachan** [comment]
@pmuir wonder if @rawlingsj could set this up?

**Comment by rawlingsj** [comment]
yeah - should just be a copy / paste, lemme make a PR

**Comment by rawlingsj** [comment]
I forgot there was an existing Jeninsfile that was building the runtime docker image, so I think that can now be replaced with the same npm style Jenkinsfile we've added to the other UI projects.  Then make a PR on fabric8-ui package.json after runtime is published so that fabric8-ui's release builds the image.  Is that all correct?

**Comment by pmuir** [comment]
Sorry gh -> email notifications are very slow today. Yes. Do it.

**Comment by jstrachan** [comment]
I think this issue is now fixed?
